spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/cruzstone;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS JAVA\;CREATE SCHEMA IF NOT EXISTS KOTLIN
    username: threeleggedhorse
    password: WfPtPCMiTyc98gs
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: JAVA